/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lankaohjelma.kayttoliittyma;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBException;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import lankaohjelma.kokoelmat.KayttajaKokoelma;
import lankaohjelma.kokoelmat.LankaKokoelma;
import lankaohjelma.kokoelmat.RistipistoTyoKokoelma;
import lankaohjelma.lankaohjelma.OmaLanka;
import lankaohjelma.lankaohjelma.XmlKasittely;
import lankaohjelma.perusluokat.Kayttaja;
import lankaohjelma.perusluokat.Lanka;
import lankaohjelma.perusluokat.RistipistoTyo;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 * Kayttaja -kayttoliittyma
 * @author Katja
 */
public class KayttajaKl extends javax.swing.JFrame {

    /**
     * Creates new form KayttajaKl
     */
    public KayttajaKl() {
        initComponents();
    }
    
    RistipistoTyo etsiRistipistoTyo;
    ArrayList<OmaLanka> omatLangat = new ArrayList<OmaLanka>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Käyttäjän nro");

        jLabel2.setText("Käyttäjän etunimi");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton1.setText("Tallenna");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Langan id", "Langan merkkinro", "Langan merkki"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Näytä langat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ristipistotyon Id", "Nimi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Näytä ristipistotyöt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel5.setText("Langan nro");

        jLabel6.setText("Osta");

        jLabel7.setText("Määrä");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Omat langat");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Käyttäjät");

        jTextPane1.setText("Valitse työ listasta tuplaklikkaamalla");
        jScrollPane3.setViewportView(jTextPane1);

        jButton4.setText("Palaa päävalikkoon");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField3)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField5)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField9)
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField10)
                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(220, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jLabel6)
                                    .addComponent(jRadioButton4)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        if (jTextField6.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "ID on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField6.requestFocus();
        }
    }//GEN-LAST:event_jTextField6ActionPerformed

     /**
     * Naytetaan langat
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DocumentBuilderFactory domFactory = DocumentBuilderFactory.newInstance();
         
        String tiedNimi = "lanka.xml";
        File nimi = new File(tiedNimi);
        if (nimi.exists()) {
      
            try {
                DocumentBuilder builder = domFactory.newDocumentBuilder();
                Document doc = builder.parse(tiedNimi);
             
                Element root = doc.getDocumentElement();
                NodeList nodelist1 = root.getElementsByTagName("Lanka");

                // Tyhjennetään taulu edellisen haun jäljiltä
                ((DefaultTableModel) jTable2.getModel()).setRowCount(0);
                String[] st= new String[3];

                for(int i=0;i<nodelist1.getLength();i++){
                    Node node=nodelist1.item(i);
                    st[0]= node.getChildNodes().item(1).getTextContent();
                    st[1]= node.getChildNodes().item(3).getTextContent();
                    st[2]= node.getChildNodes().item(5).getTextContent();        
                    ((DefaultTableModel) jTable2.getModel()).addRow(st);
                }             
            } catch (Exception ex) {
                Logger.getLogger(LankaKl.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
    }//GEN-LAST:event_jButton2ActionPerformed

     /**
     * Naytetaan ristipistotyot
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DocumentBuilderFactory domFactory = DocumentBuilderFactory.newInstance();
      
        String tiedNimi = "ristipistotyokokoelma.xml";
        File nimi = new File(tiedNimi);
        if (nimi.exists()) {
        
            try {
                DocumentBuilder builder = domFactory.newDocumentBuilder();
                Document doc = builder.parse(tiedNimi);

                Element root = doc.getDocumentElement();
                NodeList nodelist1 = root.getElementsByTagName("ristipistotyot");

                // Tyhjennetään taulu edellisen haun jäljiltä
                ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
                String[] st= new String[3];

                for(int i=0;i<nodelist1.getLength();i++){
                    Node node=nodelist1.item(i);
                    st[0]= node.getChildNodes().item(1).getTextContent();
                    st[1]= node.getChildNodes().item(3).getTextContent();                       
                    ((DefaultTableModel) jTable1.getModel()).addRow(st);
                }             
            } catch (Exception ex) {
                Logger.getLogger(KayttajaKl.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * Tallennetaan kayttaja
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // Pakollisuustarkistukset
        if (jTextField6.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "ID on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField6.requestFocus();
        } else if ("".equals(jTextField7.getText()))
            {
                JOptionPane.showMessageDialog(this, "Nimi on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
                jTextField7.requestFocus();
        } else if ("".equals(jTextField2.getText()))
            {
                JOptionPane.showMessageDialog(this, "Syötä ainakin yksi lanka", "VIRHE",JOptionPane.ERROR_MESSAGE);
                jTextField2.requestFocus();
        } else if (jTextField3.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField3.requestFocus();              
        } else if (jTextField4.getText().length() != 0 && (jTextField5.getText().length() == 0)) {                
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField5.requestFocus(); 
            
        } else if (jTextField8.getText().length() != 0 && (jTextField9.getText().length() == 0)) {                
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField9.requestFocus(); 
        } else if (jTextField10.getText().length() != 0 && (jTextField11.getText().length() == 0)) {                
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField11.requestFocus(); 
        
        // Muut tiedot
        } else {
            
            Kayttaja kayttaja = new Kayttaja();
              
            XmlKasittely kasittely = new XmlKasittely();
            String tiedNimi = "kayttajakokoelma.xml"; 
            ArrayList<Kayttaja> kayttajat = new ArrayList<Kayttaja>();
            KayttajaKokoelma kayttajaKokoelma = new KayttajaKokoelma();
        
            kayttaja.setNro(Integer.parseInt(jTextField6.getText())); 
            kayttaja.setEtunimi(jTextField7.getText());             
        
            // Lisätään käyttäjän valitsema ristipistotyö
            ArrayList<RistipistoTyo> tyolista = new ArrayList<RistipistoTyo>();
            tyolista.add(etsiRistipistoTyo);
           
            kayttaja.setRistipistotyot(tyolista);       

            // Lisätään käyttäjän valitsemat langat
            LankaKokoelma lankaKokoelma = new LankaKokoelma();
            
            // Haetaan langat, jotta voidaan näyttää ne listalla
            ArrayList LueLankaXml = null;
            try {               
                LueLankaXml = kasittely.LueLankaXml("lanka.xml");
            } catch (Exception ex) {
                Logger.getLogger(KayttajaKl.class.getName()).log(Level.SEVERE, null, ex);
            }

            KeraaLankaTieto(LueLankaXml,omatLangat);             

            // Lisätään, jos käyttäjä on valinnut lankoja
            if (omatLangat.size() != 0){
                lankaKokoelma.setOmatLangat(omatLangat);
                kayttaja.setLankaKokoelma(lankaKokoelma);
            } else {
                kayttaja.setLankaKokoelma(null);
            }            
        
            // Lisätään käyttäjä käyttäjäkokoelmaan
            kayttajat.add(kayttaja);
            kayttajaKokoelma.setKayttajat(kayttajat);
                     
            try {   
                kasittely.KirjoitaKayttajaXml(kayttajaKokoelma, tiedNimi);
            } catch (Exception ex) {
                Logger.getLogger(RistipistoTyoKl.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * Kayttaja voi tuplaklikkaamalla valita kankaan
    */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        XmlKasittely kasittely = new XmlKasittely();
        RistipistoTyoKokoelma LueTyoXml = null;
            
        jTable1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
        if (e.getClickCount() == 2) {
            JTable target = (JTable)e.getSource();
            int row = target.getSelectedRow();
           
            // Kun käyttäjä tuplaklikkaa taulukkoa, valitaan rivin id           
            Object tyoId = jTable1.getValueAt(row, 0);
            target.setSelectionBackground(Color.red);
          
            // Haetaan ristipistotyot, jotta voidaan näyttää ne listalla
            XmlKasittely kasittely = new XmlKasittely();
            RistipistoTyoKokoelma LueTyoXml = null;
            try {
                LueTyoXml = kasittely.HaeKaikkiRistipistoTyoKokoelma("ristipistotyokokoelma.xml");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(KayttajaKl.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JAXBException ex) {
                Logger.getLogger(KayttajaKl.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            ArrayList ristipistoTyot = LueTyoXml.getRistipistoTyot();
            RistipistoTyo tyo = new RistipistoTyo();
            etsiRistipistoTyo = tyo.etsiRistipistoTyo(ristipistoTyot, Integer.parseInt((String) tyoId));       
                  
        }
   }
});
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new PaaKayttoliittyma().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        if ("".equals(jTextField7.getText()))
        {
            JOptionPane.showMessageDialog(this, "Nimi on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField7.requestFocus();
        }
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField11KeyTyped
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayttajaKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayttajaKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayttajaKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayttajaKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayttajaKl().setVisible(true);
            }
        });
    }
        /**
        * Kerataan lankatiedot kayttajan syottamista kentista
        */
        private void KeraaLankaTieto(ArrayList LueLankaXml, ArrayList<OmaLanka> omatLangat) throws NumberFormatException {
        Lanka lanka = new Lanka();
        Lanka lanka2 = new Lanka();
        Lanka lanka3 = new Lanka();
        Lanka lanka4 = new Lanka();       
        
        OmaLanka omaLanka1 = new OmaLanka();
        OmaLanka omaLanka2 = new OmaLanka();
        OmaLanka omaLanka3 = new OmaLanka();
        OmaLanka omaLanka4 = new OmaLanka();   
        
        // Työssä voi olla maksimissaan 4 lankaa. Haetaan ne lankaid:n perusteella taulukosta
        int etsittava = Integer.parseInt(jTextField2.getText());
        Lanka etsiLanka = lanka.etsiLanka(LueLankaXml, etsittava);
        
        // Langan täytyy löytyä listasta
        if (etsiLanka==null){            
            JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
            jTextField2.requestFocus();
        } 
        
        lanka.setLankaid(etsiLanka.getLankaid());
        lanka.setLankanro(etsiLanka.getLankanro());
        lanka.setMerkki(etsiLanka.getMerkki());
        
        omaLanka1.setLanka(lanka);
        omaLanka1.setMaara((Integer.parseInt(jTextField3.getText())));       
        omaLanka1.setOsta(jRadioButton1.isSelected());
        
        omatLangat.add(omaLanka1);
            System.out.println("omatLangat" + omatLangat);
        
        if(!"".equals(jTextField4.getText())){
            int etsittava2 = Integer.parseInt(jTextField4.getText());
            Lanka etsiLanka2 = lanka2.etsiLanka(LueLankaXml, etsittava2);
            
            // Langan täytyy löytyä listasta
            if (etsiLanka2 == null){            
                JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
                jTextField4.requestFocus();
            } 
            
            lanka2.setLankaid(etsiLanka2.getLankaid());
            lanka2.setLankanro(etsiLanka2.getLankanro());
            lanka2.setMerkki(etsiLanka2.getMerkki());

            omaLanka2.setLanka(lanka2);
            omaLanka2.setMaara((Integer.parseInt(jTextField5.getText())));

            omaLanka2.setOsta(jRadioButton2.isSelected());
            omatLangat.add(omaLanka2);            
        }
        
        if(!"".equals(jTextField8.getText())){
            int etsittava3 = Integer.parseInt(jTextField8.getText());
            Lanka etsiLanka3 = lanka3.etsiLanka(LueLankaXml, etsittava3);
            
            // Langan täytyy löytyä listasta
            if (etsiLanka3==null){            
                JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
                jTextField8.requestFocus();
            } 
            
            lanka3.setLankaid(etsiLanka3.getLankaid());
            lanka3.setLankanro(etsiLanka3.getLankanro());
            lanka3.setMerkki(etsiLanka3.getMerkki());

            omaLanka3.setLanka(lanka3);
            omaLanka3.setMaara((Integer.parseInt(jTextField9.getText())));

            omaLanka3.setOsta(jRadioButton3.isSelected());

            omatLangat.add(omaLanka3);            
        }
        
        if(!"".equals(jTextField10.getText())){
            int etsittava4 = Integer.parseInt(jTextField10.getText());
            Lanka etsiLanka4 = lanka3.etsiLanka(LueLankaXml, etsittava4);
            
            // Langan täytyy löytyä listasta
            if (etsiLanka4==null){            
                JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
                jTextField10.requestFocus();
            } 
        
            lanka4.setLankaid(etsiLanka4.getLankaid());
            lanka4.setLankanro(etsiLanka4.getLankanro());
            lanka4.setMerkki(etsiLanka4.getMerkki());

            omaLanka4.setLanka(lanka4);
            omaLanka4.setMaara((Integer.parseInt(jTextField11.getText())));

            omaLanka4.setOsta(jRadioButton4.isSelected());

            omatLangat.add(omaLanka4);           
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
