/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lankaohjelma.kayttoliittyma;


import java.awt.event.KeyEvent;

import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import lankaohjelma.kokoelmat.RistipistoTyoKokoelma;
import lankaohjelma.lankaohjelma.TyonLanka;
import lankaohjelma.lankaohjelma.XmlKasittely;
import lankaohjelma.perusluokat.Kangas;
import lankaohjelma.perusluokat.Lanka;
import lankaohjelma.perusluokat.RistipistoTyo;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 * Ristipistotyo -kayttoliittyma
 * @author Katja
 */
public class RistipistoTyoKl extends javax.swing.JFrame {

    /**
     * Creates new form RistipistoTyoKl
     */
    public RistipistoTyoKl() {
        initComponents();
    }

    ArrayList<TyonLanka> tyonlangat = new ArrayList<TyonLanka>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Työn nro");

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setText("Leveys");

        jLabel3.setText("Korkeus");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Työn langat");

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel6.setText("Kangas");

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });

        jButton1.setText("Tallenna");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Palaa päävalikkoon");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Langan id", "Langan merkkinro", "Langan merkki"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton3.setText("Näytä langat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kankaan id", "Kankaan merkki"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jButton4.setText("Näytä kankaat");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nimi");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Ristipistotyöt");

        jLabel9.setText("Langan nro");

        jLabel10.setText("Määrä");

        jLabel4.setText("pistojen määrä");

        jLabel11.setText("pistojen määrä");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField11)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
         if (jTextField2.getText().length() == 0)
        {
        JOptionPane.showMessageDialog(this, "Leveys pitää enemmän kuin 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
        jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
    * Tallennetaan ristipistotyo
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        RistipistoTyoKokoelma tyoKokoelma = new RistipistoTyoKokoelma();
        XmlKasittely kasittely = new XmlKasittely();
        String tiedNimi = "src\\testitiedostot\\ristipistotyokokoelma.xml";        
        ArrayList<RistipistoTyo> ristipistotyot = new ArrayList<RistipistoTyo>();               
        RistipistoTyo tyo = new RistipistoTyo();
        
        //Pakolliset kenttätarkistukset
        if (jTextField1.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "ID on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();        
        } else if (jTextField2.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Leveys pitää enemmän kuin 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField2.requestFocus();
        } else if (jTextField3.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Korkeus pitää enemmän kuin 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField3.requestFocus();
        } else  if ("".equals(jTextField12.getText()))
        {
            JOptionPane.showMessageDialog(this, "Nimi on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField12.requestFocus();
        }else 
        
        // Yksi lanka on pakollinen
        if (jTextField4.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Syötä ainakin yksi lanka. Voit laittaa sille määräksi 0.", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField4.requestFocus();
        } else if (jTextField5.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField5.requestFocus();
            
        } else if (jTextField6.getText().length() != 0 && (jTextField7.getText().length() == 0)) {                
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField7.requestFocus();  
            
        } else if (jTextField8.getText().length() != 0 && (jTextField9.getText().length() == 0)) {                
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField9.requestFocus();     
            
        } else if (jTextField10.getText().length() != 0 && (jTextField11.getText().length() == 0)) {                
            JOptionPane.showMessageDialog(this, "Määrä on pakollinen. Voit syöttää määräksi 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField11.requestFocus();        
             
        } else if (jTextField14.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Kangas on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField14.requestFocus();
            
        // Muut tiedot    
        } else {
        
            // kenttien lisäys luokkaan
            tyo.tyoId = Integer.parseInt(jTextField1.getText());
            tyo.tyoNimi = jTextField12.getText();
            tyo.leveys = Integer.parseInt(jTextField2.getText());
            tyo.korkeus = Integer.parseInt(jTextField3.getText());
        
            try {
                // Haetaan langat, jotta voidaan näyttää ne listalla
                ArrayList LueLankaXml = kasittely.LueLankaXml("src\\testitiedostot\\lanka.xml");

                KeraaLankaTieto(LueLankaXml,tyonlangat);             
                tyo.setLangat(tyonlangat);    

            } catch (Exception ex) {
                Logger.getLogger(RistipistoTyoKl.class.getName()).log(Level.SEVERE, null, ex);
            }   
        
            try {
                // Haetaan kankaat, jotta voidaan näyttää ne listalla
                ArrayList LueKangasXml = kasittely.LueKangasXml("src\\testitiedostot\\kangas.xml");

                Kangas kangas = new Kangas();
                 
                // Työssä voi olla maksimissaan 4 lankaa. Haetaan ne lankaid:n perusteella taulukosta
                int etsittava = Integer.parseInt(jTextField14.getText());
                Kangas etsiKangas = kangas.etsiKangas(LueKangasXml, etsittava);
                
                // Kankaan täytyy löytyä listasta
                if (etsiKangas==null){                
                    JOptionPane.showMessageDialog(this, "Kankaan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
                    jTextField14.requestFocus();
                } 
                
                kangas.setKangasnro(etsiKangas.getKangasnro());
                kangas.setKangasMerkki(etsiKangas.getKangasMerkki());
        
                tyo.tyonKangas = kangas;     
            
                } catch (Exception ex) {
                    Logger.getLogger(RistipistoTyoKl.class.getName()).log(Level.SEVERE, null, ex);
                }   
        
                // Lisätään täytetty luokka kokoelmaan
                ristipistotyot.add(tyo);        
                tyoKokoelma.setRistipistoTyot(ristipistotyot);        
                
                try {   
                    kasittely.KirjoitaRistipistoTyoKokoelmaXml(tyoKokoelma, tiedNimi);
                } catch (Exception ex) {
                    Logger.getLogger(RistipistoTyoKl.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * Naytetaan langat taulukossa
    */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DocumentBuilderFactory domFactory = DocumentBuilderFactory.newInstance();
      
        try {
             DocumentBuilder builder = domFactory.newDocumentBuilder();
             Document doc = builder.parse("src\\testitiedostot\\lanka.xml");
             
            Element root = doc.getDocumentElement();
            NodeList nodelist1 = root.getElementsByTagName("Lanka");

            // Tyhjennetään taulu edellisen haun jäljiltä
            ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
            String[] st= new String[3];

            for(int i=0;i<nodelist1.getLength();i++){
                Node node=nodelist1.item(i);
                st[0]= node.getChildNodes().item(1).getTextContent();
                st[1]= node.getChildNodes().item(3).getTextContent();
                st[2]= node.getChildNodes().item(5).getTextContent();        
                ((DefaultTableModel) jTable1.getModel()).addRow(st);
            }             
        } catch (Exception ex) {
            Logger.getLogger(LankaKl.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * Naytetaan kankaat taulukossa
    */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            DocumentBuilderFactory domFactory = DocumentBuilderFactory.newInstance();
      
        try {
             DocumentBuilder builder = domFactory.newDocumentBuilder();
             Document doc = builder.parse("src\\testitiedostot\\kangas.xml");
             
            Element root = doc.getDocumentElement();
            NodeList nodelist1 = root.getElementsByTagName("Kangas");

            // Tyhjennetään taulu edellisen haun jäljiltä
            ((DefaultTableModel) jTable2.getModel()).setRowCount(0);
            String[] st= new String[2];

            for(int i=0;i<nodelist1.getLength();i++){
                Node node=nodelist1.item(i);
                st[0]= node.getChildNodes().item(1).getTextContent();
                st[1]= node.getChildNodes().item(3).getTextContent();                    
                ((DefaultTableModel) jTable2.getModel()).addRow(st);
            }             
        } catch (Exception ex) {
            Logger.getLogger(KangasKl.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if (jTextField1.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "ID on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        if (jTextField3.getText().length() == 0)
        {
        JOptionPane.showMessageDialog(this, "Korkeus pitää enemmän kuin 0", "VIRHE",JOptionPane.ERROR_MESSAGE);
        jTextField3.requestFocus();
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new PaaKayttoliittyma().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        if ("".equals(jTextField12.getText()))
        {
            JOptionPane.showMessageDialog(this, "Merkki on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
            jTextField12.requestFocus();
        }
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        if (jTextField14.getText().length() == 0)
        {
        JOptionPane.showMessageDialog(this, "Kangas on pakollinen tieto", "VIRHE",JOptionPane.ERROR_MESSAGE);
        jTextField14.requestFocus();
        }
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();            
        }
    }//GEN-LAST:event_jTextField14KeyTyped
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RistipistoTyoKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RistipistoTyoKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RistipistoTyoKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RistipistoTyoKl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RistipistoTyoKl().setVisible(true);
            }
        });
    }
        /**
        * Kerataan lankatiedot kayttajan syottamista kentista
        */
        private void KeraaLankaTieto(ArrayList LueLankaXml, ArrayList<TyonLanka> tyonlangat) throws NumberFormatException {
        Lanka lanka = new Lanka();
        Lanka lanka2 = new Lanka();
        Lanka lanka3 = new Lanka();
        Lanka lanka4 = new Lanka();       
        
        TyonLanka tyonLanka1 = new TyonLanka();
        TyonLanka tyonLanka2 = new TyonLanka();
        TyonLanka tyonLanka3 = new TyonLanka();
        TyonLanka tyonLanka4 = new TyonLanka();       
        
        // Työssä voi olla maksimissaan 4 lankaa. Haetaan ne lankaid:n perusteella taulukosta
        int etsittava = Integer.parseInt(jTextField4.getText());
        Lanka etsiLanka = lanka.etsiLanka(LueLankaXml, etsittava);
        
        // Langan täytyy löytyä listasta
        if (etsiLanka==null){        
            JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
            jTextField4.requestFocus();
        } 
        
        lanka.setLankaid(etsiLanka.getLankaid());
        lanka.setLankanro(etsiLanka.getLankanro());
        lanka.setMerkki(etsiLanka.getMerkki());
        
        tyonLanka1.setLankamerkki(lanka);
        tyonLanka1.setMaara(Integer.parseInt(jTextField5.getText()));
        
        tyonlangat.add(tyonLanka1);
        
        if(!"".equals(jTextField6.getText())){
            int etsittava2 = Integer.parseInt(jTextField6.getText());
            Lanka etsiLanka2 = lanka.etsiLanka(LueLankaXml, etsittava2);
            
            // Langan täytyy löytyä listasta
            if (etsiLanka2==null){            
                JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
                jTextField6.requestFocus();
            } 
        
            lanka2.setLankaid(etsiLanka2.getLankaid());
            lanka2.setLankanro(etsiLanka2.getLankanro());
            lanka2.setMerkki(etsiLanka2.getMerkki());

            tyonLanka2.setLankamerkki(lanka2);
            tyonLanka2.setMaara(Integer.parseInt(jTextField7.getText()));

            tyonlangat.add(tyonLanka2);
        }
        
        if(!"".equals(jTextField8.getText())){
            int etsittava3 = Integer.parseInt(jTextField8.getText());
            Lanka etsiLanka3 = lanka3.etsiLanka(LueLankaXml, etsittava3);
            
            // Langan täytyy löytyä listasta
            if (etsiLanka3==null){            
                JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
                jTextField8.requestFocus();
            } 
            
            lanka3.setLankaid(etsiLanka3.getLankaid());
            lanka3.setLankanro(etsiLanka3.getLankanro());
            lanka3.setMerkki(etsiLanka3.getMerkki());

            tyonLanka3.setLankamerkki(lanka3);
            tyonLanka3.setMaara(Integer.parseInt(jTextField9.getText()));

            tyonlangat.add(tyonLanka3);
        }
        
        if(!"".equals(jTextField10.getText())){
            int etsittava4 = Integer.parseInt(jTextField10.getText());
            Lanka etsiLanka4 = lanka4.etsiLanka(LueLankaXml, etsittava4);
            
            // Langan täytyy löytyä listasta
            if (etsiLanka4==null){            
                JOptionPane.showMessageDialog(this, "Langan numero täytyy löytyä listasta", "VIRHE",JOptionPane.ERROR_MESSAGE);        
                jTextField10.requestFocus();
            } 
            
            lanka4.setLankaid(etsiLanka4.getLankaid());
            lanka4.setLankanro(etsiLanka4.getLankanro());
            lanka4.setMerkki(etsiLanka4.getMerkki());

            tyonLanka4.setLankamerkki(lanka4);
            tyonLanka4.setMaara(Integer.parseInt(jTextField11.getText()));

            tyonlangat.add(tyonLanka4);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
